# Generated by Django 4.2.5 on 2023-11-29 05:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numHab', models.CharField(max_length=11, verbose_name='Número de Habilitação')),
                ('endereco', models.CharField(max_length=250)),
                ('telefone', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Escritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, unique=True)),
                ('local', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Escritório',
                'verbose_name_plural': 'Escritórios',
            },
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do veiculo')),
                ('arCond', models.BooleanField(default=False, verbose_name='Ar-condicionado')),
                ('foto', stdimage.models.StdImageField(default='car_photos/no_car.png', force_min_size=False, upload_to='car_photos', variations={}, verbose_name='Foto Carro')),
            ],
            managers=[
                ('tipoquery', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('tipoveiculo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='veiculos.tipoveiculo')),
                ('numPortas', models.IntegerField(choices=[(2, '2 portas'), (4, '4 portas')], default=4, verbose_name='Número de Portas')),
                ('dirHidraulica', models.BooleanField(default=False, verbose_name='Direção Hidráulica')),
                ('cambioAuto', models.BooleanField(default=False, verbose_name='Cambio Automático')),
            ],
            options={
                'verbose_name': 'Automovel',
                'verbose_name_plural': 'Automóveis',
            },
            bases=('veiculos.tipoveiculo',),
            managers=[
                ('tipoquery', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Onibus',
            fields=[
                ('tipoveiculo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='veiculos.tipoveiculo')),
                ('numPassageiros', models.IntegerField(default=32, validators=[django.core.validators.MaxValueValidator(104), django.core.validators.MinValueValidator(32)], verbose_name='Número de Passageiros')),
                ('leito', models.BooleanField(default=False)),
                ('sanitario', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Onibus',
                'verbose_name_plural': 'Onibus',
            },
            bases=('veiculos.tipoveiculo',),
            managers=[
                ('tipoquery', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataProxManut', models.DateField(verbose_name='Data da próxima Manutenção')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('tipoVeiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='veiculos.tipoveiculo', verbose_name='Veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('duracao', models.IntegerField(verbose_name='Duração do Contrato em dias')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos.cliente')),
                ('numEscritorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos.escritorio')),
                ('veiculo', models.ForeignKey(limit_choices_to={'disponivel': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos.veiculo')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
