# Generated by Django 4.2.7 on 2023-11-24 06:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("veiculos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="escritorio",
            name="nome",
            field=models.CharField(default="ss", max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="onibus",
            name="numPassageiros",
            field=models.IntegerField(
                default=32,
                validators=[
                    django.core.validators.MaxValueValidator(104),
                    django.core.validators.MinValueValidator(32),
                ],
                verbose_name="Número de Passageiros",
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="tipoVeiculo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="veiculos.tipoveiculo",
                verbose_name="Veiculo",
            ),
        ),
    ]
