# Generated by Django 4.2.5 on 2023-12-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='duracao',
            field=models.DateField(verbose_name='Duração do Contrato'),
        ),
    ]
