# Generated by Django 4.2.5 on 2023-11-27 18:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_escritorio_nome_alter_onibus_numpassageiros_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='automovel',
            managers=[
                ('tipoquery', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='onibus',
            managers=[
                ('tipoquery', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tipoveiculo',
            managers=[
                ('tipoquery', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='tipoveiculo',
            name='foto',
            field=stdimage.models.StdImageField(default='car_photos/no_car.png', force_min_size=False, upload_to='car_photos', variations={'thumb': {'crop': True, 'height': 600, 'width': 600}}, verbose_name='Foto Carro'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='veiculos.cliente'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numEscritorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.escritorio'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='veiculo',
            field=models.ForeignKey(limit_choices_to={'disponivel': True}, on_delete=django.db.models.deletion.DO_NOTHING, to='veiculos.veiculo'),
        ),
        migrations.AlterField(
            model_name='tipoveiculo',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do veiculo'),
        ),
    ]
