# Generated by Django 4.2.5 on 2023-12-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_alter_contrato_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numHab',
            field=models.CharField(max_length=11, unique=True, verbose_name='Número de Habilitação'),
        ),
    ]
